# Generated by Django 4.2.3 on 2023-10-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_reviewer_name_productreview_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
