# Generated by Django 4.2.3 on 2023-10-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_incart',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
