# Generated by Django 4.2.3 on 2023-10-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_quantity_incart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_incart',
        ),
    ]
